Repository WeatherTago/backend, pull requests merged in 2025-06, with the labels that each got.

#10 [Feat] notice 크롤링 기능 개발
  build.gradle
  src/main/java/com/tave/weathertago/WeathertagoApplication.java
  src/main/java/com/tave/weathertago/controller/Notice/NoticeCrawlingController.java
  src/main/java/com/tave/weathertago/controller/Notice/NoticeRestController.java
  src/main/java/com/tave/weathertago/domain/Notice.java
  src/main/java/com/tave/weathertago/repository/NoticeRepository.java
  src/main/java/com/tave/weathertago/service/Notice/NoticeCrawlingService.java
  src/main/java/com/tave/weathertago/service/Notice/NoticeCrawlingServiceImpl.java
  src/main/java/com/tave/weathertago/service/Notice/NoticeQueryServiceImpl.java
Labels: :sparkles: Feature, ⚙️Setting

#11 [Feat] 카카오 소셜 로그인 및 JWT 토큰 재발급 기능 구현
  build.gradle
  src/main/java/com/tave/weathertago/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tave/weathertago/apiPayload/exception/handler/UserHandler.java
  src/main/java/com/tave/weathertago/config/security/SecurityConfig.java
  src/main/java/com/tave/weathertago/config/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/tave/weathertago/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/tave/weathertago/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/tave/weathertago/config/security/properties/Constants.java
  src/main/java/com/tave/weathertago/config/security/properties/JwtProperties.java
  src/main/java/com/tave/weathertago/controller/AuthController.java
  src/main/java/com/tave/weathertago/converter/AuthConverter.java
  src/main/java/com/tave/weathertago/domain/User.java
  src/main/java/com/tave/weathertago/dto/Auth/AuthRequestDTO.java
  src/main/java/com/tave/weathertago/dto/Auth/AuthResponseDTO.java
  src/main/java/com/tave/weathertago/dto/Auth/KakaoUserInfo.java
  src/main/java/com/tave/weathertago/infrastructure/KakaoApiClient.java
  src/main/java/com/tave/weathertago/repository/UserRepository.java
  src/main/java/com/tave/weathertago/service/auth/AuthService.java
  src/main/java/com/tave/weathertago/service/auth/AuthServiceImpl.java
Labels: :sparkles: Feature, ⚙️Setting

#31 [Fix] JWT 관련 커스텀 에러 핸들링 설정
  src/main/java/com/tave/weathertago/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tave/weathertago/config/security/SecurityConfig.java
  src/main/java/com/tave/weathertago/config/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/tave/weathertago/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/tave/weathertago/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/tave/weathertago/service/auth/AuthServiceImpl.java
Labels: :recycle: Refactor, 🐛Bug

#41 [Feat] Redis 설정
  build.gradle
  src/main/java/com/tave/weathertago/config/RedisConfig.java
Labels: ⚙️Setting
