Repository WeatherTago/backend, pull requests merged in 2025-07, with the labels that each got.

#49 [Feat] 기상청 날씨 불러오기 구현
  .github/workflows/cd-dev.yml
  .gitignore
  src/main/java/com/tave/weathertago/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tave/weathertago/apiPayload/exception/handler/WeatherHandler.java
  src/main/java/com/tave/weathertago/config/RestClientConfig.java
  src/main/java/com/tave/weathertago/domain/Station.java
  src/main/java/com/tave/weathertago/dto/weather/WeatherApiResponseDTO.java
  src/main/java/com/tave/weathertago/dto/weather/WeatherResponseDTO.java
  src/main/java/com/tave/weathertago/infrastructure/WeatherApiClient.java
  src/test/java/com/tave/weathertago/infrastructure/WeatherApiClientTest.java
Labels: :sparkles: Feature

#64 [Feat] 즐겨찾기 DB추가
  ddl_Favorite.sql
Labels: :sparkles: Feature

#66 [Feat] stationId추가
  src/main/java/com/tave/weathertago/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tave/weathertago/converter/FavoriteConverter.java
  src/main/java/com/tave/weathertago/converter/SubwayPathConverter.java
  src/main/java/com/tave/weathertago/dto/favorite/FavoriteResponseDTO.java
  src/main/java/com/tave/weathertago/dto/station/SubwayPathDTO.java
  src/main/java/com/tave/weathertago/dto/station/SubwayPathResponseDTO.java
  src/main/java/com/tave/weathertago/infrastructure/SubwayOpenApiClient.java
  src/main/java/com/tave/weathertago/service/station/SubwayPathQueryServiceImpl.java
Labels: :sparkles: Feature

#74 [feat] 역 정보 파라미터 변경
  src/main/java/com/tave/weathertago/controller/stationController/StationRestController.java
  src/main/java/com/tave/weathertago/service/station/StationQueryService.java
  src/main/java/com/tave/weathertago/service/station/StationQueryServiceImpl.java
Labels: :sparkles: Feature

#79 [feat] 길찾기 파라미터 변경
  src/main/java/com/tave/weathertago/controller/stationController/SubwayPathController.java
  src/main/java/com/tave/weathertago/converter/SubwayPathConverter.java
  src/main/java/com/tave/weathertago/dto/station/SubwayPathDTO.java
  src/main/java/com/tave/weathertago/repository/StationRepository.java
  src/main/java/com/tave/weathertago/service/station/SubwayPathQueryService.java
  src/main/java/com/tave/weathertago/service/station/SubwayPathQueryServiceImpl.java
Labels: :sparkles: Feature

#81 [Fix] alarm 기능
  src/main/java/com/tave/weathertago/converter/AlarmConverter.java
  src/main/java/com/tave/weathertago/domain/Alarm.java
  src/main/java/com/tave/weathertago/domain/AlarmPeriod.java
  src/main/java/com/tave/weathertago/domain/Direction.java
  src/main/java/com/tave/weathertago/dto/alarm/AlarmRequestDTO.java
  src/main/java/com/tave/weathertago/dto/alarm/AlarmResponseDTO.java
  src/main/java/com/tave/weathertago/service/alarm/AlarmCommandServiceImpl.java
  src/main/java/com/tave/weathertago/service/alarm/AlarmQueryServiceImpl.java
  src/main/java/com/tave/weathertago/service/alarm/AlarmSendServiceImpl.java
Labels: :sparkles: Feature, :recycle: Refactor

#83 [Refactor] notice and alarm
  src/main/java/com/tave/weathertago/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tave/weathertago/apiPayload/exception/handler/AlarmHandler.java
  src/main/java/com/tave/weathertago/apiPayload/exception/handler/NoticeHandler.java
  src/main/java/com/tave/weathertago/controller/Notice/NoticeRestController.java
  src/main/java/com/tave/weathertago/controller/alarm/AlarmController.java
  src/main/java/com/tave/weathertago/controller/alarm/AlarmFcmController.java
  src/main/java/com/tave/weathertago/controller/alarm/AlarmRestController.java
  src/main/java/com/tave/weathertago/domain/Alarm.java
  src/main/java/com/tave/weathertago/service/Notice/NoticeCrawlingServiceImpl.java
  src/main/java/com/tave/weathertago/service/Notice/NoticeQueryService.java
  src/main/java/com/tave/weathertago/service/Notice/NoticeQueryServiceImpl.java
  src/main/java/com/tave/weathertago/service/alarm/AlarmCommandServiceImpl.java
  src/main/java/com/tave/weathertago/service/alarm/AlarmQueryService.java
  src/main/java/com/tave/weathertago/service/alarm/AlarmQueryServiceImpl.java
  src/main/java/com/tave/weathertago/service/alarm/AlarmSendServiceImpl.java
Labels: :recycle: Refactor

#86 [Fix] alarm send service
  redis.conf
  src/main/java/com/tave/weathertago/repository/AlarmRepository.java
  src/main/java/com/tave/weathertago/service/alarm/AlarmSendServiceImpl.java
Labels: :recycle: Refactor

#75 [Feat] AI 서버 연동
  src/main/java/com/tave/weathertago/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tave/weathertago/apiPayload/exception/handler/CongestionHandler.java
  src/main/java/com/tave/weathertago/converter/PredictionConverter.java
  src/main/java/com/tave/weathertago/dto/prediction/AiServerResponseDTO.java
  src/main/java/com/tave/weathertago/dto/prediction/PredictionRequestDTO.java
  src/main/java/com/tave/weathertago/dto/prediction/PredictionResponseDTO.java
  src/main/java/com/tave/weathertago/dto/prediction/PredictionWithWeatherResponseDTO.java
  src/main/java/com/tave/weathertago/infrastructure/AiPredictionClient.java
  src/main/java/com/tave/weathertago/infrastructure/WeatherApiClient.java
  src/main/java/com/tave/weathertago/service/congestion/CongestionQueryService.java
  src/main/java/com/tave/weathertago/service/congestion/CongestionQueryServiceImpl.java
  src/test/java/com/tave/weathertago/infrastructure/AiPredictionClientTest.java
Labels: :sparkles: Feature

#116 [Feat] 날씨만 받아오는 서비스 추가
  src/main/java/com/tave/weathertago/service/congestion/CongestionQueryServiceImpl.java
  src/main/java/com/tave/weathertago/service/station/StationQueryServiceImpl.java
  src/main/java/com/tave/weathertago/service/weather/WeatherQueryService.java
  src/main/java/com/tave/weathertago/service/weather/WeatherQueryServiceImpl.java
Labels: :sparkles: Feature

#142 [Fix] refresh token 관리 방식 redis로 변경
  src/main/java/com/tave/weathertago/apiPayload/exception/handler/AuthHandler.java
  src/main/java/com/tave/weathertago/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/tave/weathertago/domain/User.java
  src/main/java/com/tave/weathertago/service/auth/AuthServiceImpl.java
Labels: :recycle: Refactor

#144 [Feat]역 상세 정보 추가(전화번호, 주소)
  src/main/java/com/tave/weathertago/controller/stationController/StationRestController.java
  src/main/java/com/tave/weathertago/converter/StationConverter.java
  src/main/java/com/tave/weathertago/domain/Station.java
  src/main/java/com/tave/weathertago/dto/station/StationResponseDTO.java
  src/main/java/com/tave/weathertago/infrastructure/csv/StationCsvImporter.java
  src/main/java/com/tave/weathertago/service/station/StationQueryService.java
  src/main/java/com/tave/weathertago/service/station/StationQueryServiceImpl.java
  src/main/resources/stationInfo.csv
Labels: :sparkles: Feature

#145 [Fix] 기상청에서 날씨 받아오는 시간대 수정
  src/main/java/com/tave/weathertago/infrastructure/WeatherApiClient.java
Labels: :sparkles: Feature

#147 [Feat] 지하철 역 3일치 시간대별 날씨, 혼잡대 조회 API 구현
  src/main/java/com/tave/weathertago/controller/stationController/StationRestController.java
  src/main/java/com/tave/weathertago/converter/StationConverter.java
  src/main/java/com/tave/weathertago/dto/station/StationResponseDTO.java
  src/main/java/com/tave/weathertago/service/station/StationQueryService.java
  src/main/java/com/tave/weathertago/service/station/StationQueryServiceImpl.java
Labels: :sparkles: Feature

#151 [Feat] 로그아웃, 회원탈퇴 API 구현
  src/main/java/com/tave/weathertago/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/tave/weathertago/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/tave/weathertago/controller/auth/AuthController.java
  src/main/java/com/tave/weathertago/controller/user/UserRestController.java
  src/main/java/com/tave/weathertago/domain/User.java
  src/main/java/com/tave/weathertago/service/auth/AuthService.java
  src/main/java/com/tave/weathertago/service/auth/AuthServiceImpl.java
  src/main/java/com/tave/weathertago/service/user/UserCommandService.java
  src/main/java/com/tave/weathertago/service/user/UserCommandServiceImpl.java
Labels: :sparkles: Feature, :recycle: Refactor

#152 fix: 신규 유저 여부 판단하는 로직 개선
  src/main/java/com/tave/weathertago/service/auth/AuthServiceImpl.java
Labels: 🐛Bug

#156 [Fix] 지하철역 상태 조회 응답 형식 수정 및 타입 오류 해결
  src/main/java/com/tave/weathertago/controller/stationController/StationRestController.java
  src/main/java/com/tave/weathertago/converter/StationConverter.java
  src/main/java/com/tave/weathertago/dto/station/StationResponseDTO.java
  src/main/java/com/tave/weathertago/service/station/StationQueryService.java
  src/main/java/com/tave/weathertago/service/station/StationQueryServiceImpl.java
Labels: :recycle: Refactor, 🐛Bug

#163 [Fix] 로그인 인증 적용 설정 및 테스트 컨트롤러 제거
  src/main/java/com/tave/weathertago/config/security/SecurityConfig.java
  src/main/java/com/tave/weathertago/controller/CongestionTestController.java
  src/main/java/com/tave/weathertago/controller/WeatherTestController.java
Labels: :sparkles: Feature

#165 feat:15 swagger tag달기
  src/main/java/com/tave/weathertago/controller/favorite/FavoriteRestController.java
  src/main/java/com/tave/weathertago/controller/stationController/StationRestController.java
  src/main/java/com/tave/weathertago/controller/stationController/SubwayPathController.java
Labels: :sparkles: Feature

#171 [Refactor] security 관련 폴더 구조 수정
  src/main/java/com/tave/weathertago/config/SecurityConfig.java
  src/main/java/com/tave/weathertago/controller/auth/AuthController.java
  src/main/java/com/tave/weathertago/controller/user/UserRestController.java
  src/main/java/com/tave/weathertago/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/tave/weathertago/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/tave/weathertago/security/jwt/JwtTokenProvider.java
  src/main/java/com/tave/weathertago/security/properties/Constants.java
  src/main/java/com/tave/weathertago/security/properties/JwtProperties.java
  src/main/java/com/tave/weathertago/service/auth/AuthServiceImpl.java
  src/main/java/com/tave/weathertago/service/user/UserCommandServiceImpl.java
Labels: :recycle: Refactor

#178 [Chore] auth 관련 로그 추가
  src/main/java/com/tave/weathertago/service/auth/AuthServiceImpl.java
Labels: 📝Docs

#179 [Fix] 날씨 api fallback 제거 및 basetime 수정
  src/main/java/com/tave/weathertago/infrastructure/WeatherApiClient.java
Labels: 🐛Bug

#180 [Chore] 혼잡도 응답 시간 측정 log 추가
  src/main/java/com/tave/weathertago/service/station/StationQueryServiceImpl.java
Labels: :recycle: Refactor
